spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/vibeclipdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8000

vibeclip:
  jwt:
    secret: c3VwZXJzZWNyZXRrZXlmb3Jqd3R0b2tlbnNpZ25pbmdhbmR2ZXJpZmljYXRpb24=
    expiration-ms: 3600000

logging:
  level:
    org.hibernate.SQL: DEBUG

